### ISSUE TITLE
How were you able to get the live preview within text?

### ISSUE THREAD

**Issue by afang** [brrd/Abricotine#1]
I dived into the code a bit but wasn't able to figure out how you got the inline preview within the text editor. I will try to port this to OSx.

**Comment by sbruchmann** [comment]
Since [Abricotine](https://github.com/brrd/Abricotine/) is built on top of [CodeMirror](codemirror.net), it is quite trivial to implement this by using [doc.markText()](https://codemirror.net/doc/manual.html#markText) (see `replacedWith`).

The corresponding file in Abricotine is [app/renderer/cm-extend-autopreview.js](https://github.com/brrd/Abricotine/blob/3aedaf7d5523d1e54387e9f9538388db382803b8/app/renderer/cm-extend-autopreview.js).

**Comment by brrd** [comment]
@sbruchmann Thanks for answering!

@afang Good news for the OSx port. Don't hesitate to ask questions if you need.
