### ISSUE TITLE
Window controls integrated into UI

### ISSUE THREAD

**Issue by codesharkasm** [brrd/Abricotine#109]
The menu bar is ugly on Win10.

**Comment by brrd** [comment]
I can't reproduce this issue. Please give more detail about it. A screenshot?

**Comment by codesharkasm** [comment]
Don't know about you, but 
![image](https://cloud.githubusercontent.com/assets/8107485/19867825/c2d6fe82-9f7b-11e6-925c-8693c35a1eb4.png) is kind of ugly...

**Comment by darahak** [comment]
I don't think Electron allows visual customization for the menus.
This would probably require re-implementing a menu API using HTML/CSS/JS.

**Comment by brrd** [comment]
@codesharkasm Actually I think I still don't understand what you are asking for. Well, I got that you think the app is ugly, so I assume you want to change the menu bar appearance as @darahak says? This is not telling us why you think this is ugly and how you want it to be. Please be constructive.

Personally I really don't like when apps are reinventing the wheel by making their own UI. I think it's a waste of developing time and it's counterproductive in term of performances. And it reminds me of all those horrible flash/java apps with their old-fashioned custom UI.

In my opinion it's not apps purpose to manage this. You already can hide the menu bar if you want. Otherwise you should probably change your OS if you don't like its UI 😕
