### ISSUE TITLE
Load hunspell dictionaries in addition to OS dictionaries

### ISSUE THREAD

**Issue by zommuter** [brrd/abricotine#134]
While I have the directories `de_DE`, `en_US`, `es`, `fr_FR` in `%appdata%\Abricotine\app\dict`, Abricotine instead let's me choose between three local variants of German (`de_DE`, `de_CH`, `de_AT`) instead:

![abricotine-spellcheck](https://cloud.githubusercontent.com/assets/3686260/20795485/b7deff3e-b7d1-11e6-9d83-8e34742ab9e9.png)

Any idea what went wrong? My Windows locale is indeed `de_CH` if that matters.

**Comment by brrd** [comment]
This is the expected behavior.

Check the documentation: https://github.com/brrd/Abricotine/blob/master/docs/configuration.md#spell-checker-dictionaries

When the OS includes native dictionaries then hunspell dictionaries are ignored and Abricotine loads system dictionaries instead. If you need another language, just install it from your OS preferences.

**Comment by zommuter** [comment]
Thanks. That seems a bit counter-intuitive at first, would it be possible to use OS settings and then additionally consider the provided hunspell files (overriding OS settings for duplicates)? I don't actually know what kind of Windows setting provides those languages, the only MS thing I have installed is Office but that also has `en_US` available, so I don't have an idea which "OS preferences" the documentation refers to. This could also be a problem for users without admin permissions I guess.

**Comment by brrd** [comment]
On windows you can add dictionaries from the language settings in the control panel. This option is interesting because it makes dictionaries consistent among programs, which is especially useful when you add your own custom entries. But mixing the two behaviors is a good idea.

> overriding OS settings for duplicates

I would override hunspell instead. We can maybe let the user choose with an option.

**Comment by zommuter** [comment]
@brrd An option for selecting the preferred data indeed sounds best, thanks for reconsidering.

**Comment by brrd** [comment]
Abricotine 1.1 now uses nspell dictionaries on all platforms. See https://github.com/brrd/abricotine/blob/master/docs/configuration.md#spell-checker-dictionaries
