### ISSUE TITLE
Rename "Copy as HTML" menu to "Copy as Rich Text"

### ISSUE THREAD

**Issue by ghost** [brrd/Abricotine#186]
The "Copy as html" feature from the edit menu copies only the pure text without any html.

Example: Assume this text as given
```
# Test

test
```

"Copy as html" will copy this to the clipboard
```
Test
test
```

So it will remove the markdown (here: the hashtag) but will not add html tags.

**Comment by brrd** [comment]
This is the expected behavior. This command actually copies the content as rich text (try to paste it in LibreOffice or Microsoft Word and you will see format is preserved). If you paste it in a normal text control then plain text will be pasted.

Maybe this would be clearer if we rename this menu in "Copy as Rich Text"?

**Comment by krbaehrle** [comment]
> Maybe this would be clearer if we rename this menu in "Copy as Rich Text"?

Yes, definitively. It is very misleading. I expected html code that I can paste in an html file.

**Comment by Jumanjii** [comment]
I was working on it when I hit a wall during translation in the other languages.
Is "Copy with formatting" would not be better?

en : Copy with Formatting
fr : Copier avec Mise en forme
es: Copiar con Formato
....

What do you think about it? :-)
