### ISSUE TITLE
Makefile automatic variables are wrongly rendered in "code" blocks.

### ISSUE THREAD

**Issue by 399man** [brrd/Abricotine#210]
Within \<pre\> blocks html entities are properly interpreted and rendered, but

within \`\`\` blocks :
 - html entities are not interpreted
 - Makefile automatic variables are wrongly interpreted

within \<code\> blocks : 
 - Makefile automatic variables are wrongly interpreted
 - CSS is somewhat broken (git theme)

Tested with the 0.6.0 release.
<hr />

This is the code I wrote:

\<pre\>
debug: image.iso  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;qemu-system-i386 -monitor stdio -cdrom \&dollar\;\&lt\; -s -S
\</pre\>

\<pre\>
debug: image.iso  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;qemu-system-i386 -monitor stdio -cdrom $< -s -S
\</pre\>

\`\`\`
debug: image.iso  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;qemu-system-i386 -monitor stdio -cdrom \&dollar\;\&lt\; -s -S
\`\`\`

\`\`\`
debug: image.iso  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;qemu-system-i386 -monitor stdio -cdrom $< -s -S
\`\`\`

\<code\>
debug: image.iso  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;qemu-system-i386 -monitor stdio -cdrom \&dollar\;\&lt\; -s -S
\</code\>

\<code\>
debug: image.iso  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;qemu-system-i386 -monitor stdio -cdrom $< -s -S
\</code\>

and how it was rendered:

![makefilecode](https://user-images.githubusercontent.com/8896676/32722967-0ac4b36e-c86c-11e7-88ac-cc62ee803602.png)

**Comment by brrd** [comment]
I guess you are talking about HTML export?

**Comment by 399man** [comment]
Export and "live" preview in the web browser.

**Comment by brrd** [comment]
> within \`\`\` blocks :
> html entities are not interpreted

They are not supposed to be interpreted. \`\`\` is supposed to display code, so markdown compilers won't translate anything in it. Unlike `<pre>` which is a HTML tag. In markdown, HTML tags are not converted, they are kept as they are in the document. Your browser is responsible for interpreting HTML entities in it.
So I don't see any problem in the behavior you describe.

> within `<code>` blocks :
> CSS is somewhat broken (git theme)

Here again this is the expected behavior. According to the specs `<code>` is an inline element, while `<pre>` is a block.

> Makefile automatic variables are wrongly interpreted

I don't think those variables are related to makefile. They are obviously coming from https://github.com/brrd/Abricotine/blob/58f25efe05b78227ea609cc9f06349c2a9650de2/app/renderer/export-html.js#L49
I'll create an issue dedicated to this.
