### ISSUE TITLE
Usage of double modifiers

### ISSUE THREAD

**Issue by fbruetting** [brrd/Abricotine#214]
For creating a heading, you currently have to press `Ctrl + F#`. On most laptops, you have to press the `Fn` key additionally, so you need to use two modifiers simultaneoisly for one action. Please don’t make use of levels on function keys, that’s bad UX.

Instead you could use just `Ctrl + #` – which is the hotkey at LibreOffice, by the way. In fact, reusing hotkeys of similar, big programs (i.e. LibreOffice and gedit) would enhance UX throughout text editing in general.

**Comment by brrd** [comment]
> Please don’t make use of levels on function keys, that’s bad UX.

IMHO bad UX is having to press additionally the Fn key in order to access function keys. It used to be very common to have Ctrl + Fn hotkeys in applications, until Apple made those keys useless by changing them into gimmicky switches. In most PC, user can decide to use function keys the normal way by toggling an option in the BIOS.

But I agree we must be aware of this kind of issue, and anyway I find your LibreOffice argument very relevant, so let's do this.

**Comment by fbruetting** [comment]
Let’s be honest, most people use media keys way more often than Fn keys. And while the Fn key mappings could easily be mapped to regular key mappings, that won’t be a good idea for media keys. So I don’t see a relevant argument for using Fn keys with additional level keys. ;)
