### ISSUE TITLE
Latex in HTML broken

### ISSUE THREAD

**Issue by thj01** [brrd/Abricotine#218]
When exported to HTML the Latex output is missing.

When i normally use Latex in HTML i wrap it "correctly" with
in a classed _span_ element when it is inline and a _div_ when it is in a block, which in my opinion is the right way to do it in HTML5.

`<span class="foo1">\( L_aT^eX \)<\span>`
`<div class="foo2">\( L_aT^eX \)<\div>`

But in the exported code from Abricotine it is done as
`<script type="math/tex">D = b^2 - 4ac</script>`
... and is not shown on the HTML output

Abricotine is the best no BS offline editor i have run into, so i would love to have this problem solved.

NB It is working beautifully in Abricotine itself :)
tested on Win10 and Ubuntu 16.04

And a PDF printer and TOC would be really appreciated.

**Comment by thj01** [comment]
There must be something wrong with the "if" structure in the `<script>`-section.

If i just put this in the templates head section:

`			<script type="text/javascript"
				src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML">  
			</script>`

it works like a charm (but still a problem to control with CSS)....

Is the style tag not a remiscent from XHTML ??

NB ... im unsure if the highlight.js works ....

**Comment by brrd** [comment]
I think I don't understand your issue.

Abricotine does not support Latex, but maybe you mean "math written in LateX"? If so, you should wrap your code with `$$` instead of using span or div (because in markdown HTML is not interpreted, it is kept as is for the browser).

> But in the exported code from Abricotine it is done as
> <script type="math/tex">D = b^2 - 4ac</script>
> ... and is not shown on the HTML output

How did you get this output? 
If you write `$$(L_aT^eX)$$` in Abricotine, the produced HTML should be `<script type="math/tex; mode=display">(L_aT^eX)</script>`. The `mode=display` is expected to make MathJax work here.

**Comment by thj01** [comment]
Input i abricotine
`$$ x = \frac{-b \pm sqrt D}{2a}$$`

Output in HTML file
`<script type="math/tex; mode=display">x = \frac{-b \pm sqrt D}{2a}</script>`

There is no visible output in the browser (chrome or firefox)

If i remove the styling section:
`                if (document.querySelector("script[type=\"math/tex; mode=display\"]") !== null) {  
                    var mathjax = document.createElement("script");  
                    mathjax.src = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML";  
                    document.head.appendChild(mathjax);  
                }`

With (my solution):
`<script type="text/javascript"
       src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML">
</script>
`
There is visible output in the browser, but it does not conform to HTML5 and is not stylable with CSS

The Latex code ought to be in an ordinary `<span>` or `<div>` element to conform with HTML5 eg:
for an inline-element
`<span class="latex_inline">\( x = \frac{-b \pm sqrt D}{2a} \)<\span>`
for a block-element
`<dic class="latex_block">$$ x = \frac{-b \pm sqrt D}{2a} $$<\div>`

In this way it is possible to use CSS to style the element containing the Latexcode, and it is only necessary with the scripting i suggest from above (http://docs.mathjax.org/en/latest/start.html)

**Comment by brrd** [comment]
> There is no visible output in the browser (chrome or firefox)

This should be visible, this is a bug. Can you copy here the full source of the page please?

> With (my solution):
> <script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"> </script>

"Your" solution does basically the same, but it loads MathJax in every document regardless of its usefulness. It is not a good solution in term of performance, this is why we should fix this bug instead in my opinion.

> The Latex code ought to be in an ordinary <span> or <div> element to conform with HTML5 eg:

This is a separate issue which deserves a dedicated thread IMO.
Anyway, this markup comes from https://github.com/GitbookIO/kramed. It appears to be perfectly HTML5 compliant according to https://validator.w3.org/nu/#textarea

**Comment by thj01** [comment]
I have some testing now.

The problem is as follows: I wanted to make a TOC with a javascript in the HTML-output, so i used a javascript from http://www.whitsoftdev.com/, which is simple and under MIT-lilcense.

To make this work i had to add someting to the `<body>` tag:
`<body onload="generateTOC(document.getElementById('toc'));">`

This breaks the script that makes Latex and highligting.js work. I can not see how it does that, as the code seems valid. It seems like the onload command in the `<body`-tag, that the TOC needs annuls the script???

Here you have my full template.html and *.md file i have used for testing:

- http://www.vidas.dk/hjemmeside/files/abricotine/template.html
    - i have outcommended the original script and inserted the needed files so that it works after my needs
- http://www.vidas.dk/hjemmeside/files/abricotine/abricotine.md
    - The file i have used for testing.
***
About the style element should i raise the problem in https://github.com/GitbookIO/kramed?
The style element works, and is not illegal - but it is not CSS'able - which is a big part of HTML5

**Comment by brrd** [comment]
I'm closing this issue since it doesn't come from Abricotine but from your custom template.

> To make this work i had to add someting to the <body> tag: <body onload="generateTOC(document.getElementById('toc'));">

By doing this you probably override something. You should try to add this function call to the onload script instead:

```javascript
window.onload = function() {
    generateTOC(document.getElementById('toc'));
    if (document.querySelector("script[type=\"math/tex; mode=display\"]") !== null) {
    ....
```

If you still encounter issues then something probably doesn't work in your script toc.js.

>  The style element works, and is not illegal - but it is not CSS'able - which is a big part of HTML5

Formulas are rendered by MathJax so the rendered element would remain the same, no matter which element you decide to use as input. Using a span or a div or whatever won't change anything about this. If you want to modify the style then you will have to style MathJax elements.

**Comment by RoyiAvital** [comment]
@brrd ,
If I get correctly what's [written on MathJax](https://docs.mathjax.org/en/v1.0/model.html) then:

The output `<script type="math/tex">x+\sqrt{1-x^2}</script>` should be for Inline Math.

The output `<script type="math/tex; mode=display">
  \sum_{n=1}^\infty {1\over n^2} = {\pi^2\over 6}
</script>` should be for Display Math.

Does Abricotine always generate Display Math?
Because the output looks like it is always inline (No matter what delimiters are chosen).

**Comment by brrd** [comment]
@RoyiAvital this question is not related to the current thread 😭 
Abricotine doesn't support distinction between inline and displayed math: #75.
