### ISSUE TITLE
Menu bar disappears

### ISSUE THREAD

**Issue by amerocu** [brrd/Abricotine#236]
There is something wrong with keyboard shortcut in Linux
I can hide and show the menu bar pressing only "Alt" and nothing happens using "Alt+Shift+T".

If I hide the menu bar with the menu bar button and then press "Alt" the menù bar appears but disappears when I focus on another application.

After pressing the "Alt" key the bar looks like this:
![screenshot from 2018-02-15 18 34 09](https://user-images.githubusercontent.com/1136288/36271470-00d0cbec-127f-11e8-8658-eb491fb362bb.png)

The steps to reproduce this bug are:
1) Hide the menu bar with Menu Bar -> View -> Show Menu Bar
2) Show the menu bar by pressing the "Alt" key
3) Change the window focus to another program window

You can see that the menu bar disappears, and after 2) the menu bar looks like the image above.

OS: Linux, Elementary OS
Abicotine: 428828b1a7d3f9eaf72f5ed59ce3e9430866a9bd and 92803d5b4a959f25600da8466d9546e9acb79612

**Comment by brrd** [comment]
I think what you describe is the expected behavior:

* When "Show Menu Bar" is checked, the menu bar is always visible.
* When "Show Menu Bar" is unchecked, the menu bar is always hidden and you need to press Alt to show it. When the app is unfocused then the bar disappears.

>  I can hide and show the menu bar pressing only "Alt" and nothing happens using "Alt+Shift+T".

What "Alt+Shift+T" is supposed to do?
