### ISSUE TITLE
IRC Channel

### ISSUE THREAD

**Issue by clawoflight** [brrd/abricotine#247]
Would you consider opening an IRC channel?

I'm thinking about starting to work on this in the summer, but the high amount of issues coming in and the fact that mostly only you work on it make that a daunting task.
I think it would be much easier to coordinate if an additional, more real-time communication channel was available.

**Comment by DanielOaks** [comment]
fwiw I'd be happy to sit in a channel and ping away at it as well, try to get some work done on that PR and maybe some other stuff :)

**Comment by brrd** [comment]
I understand your request but unfortunately I have currently very few time to give to Abricotine and I'm afraid I wouldn't be able to answer in real time to this channel. I will be working on professional projects during the whole summer and I already know that I will be very busy 😕 

I'm trying to answer as soon as I can to issues and pull requests but I can not really do more in this time. This is why I give very few contributions. I'm comfortable with Github PR and issues because it allows me to answer as soon as I have time and it keeps track of the whole conversation and diff. This remains the best way to work on this project IMO.

But if you really want to open an IRC channel to communicate together then go ahead of course, this can be a good way to stimulate contributions. I would join if possible but I personally can not guarantee that I'll be able to participate regularly this summer.

> the fact that mostly only you work on it make that a daunting task

I totally understand your point. I also know some parts of the code are not easy to understand. When I started this project 3 years ago it was supposed to be a training project. This was my first try with Electron/Node.js and I made several mistakes which remains in the code still today. I would love to rewrite the whole thing in a better way today but this would definitely be a very huge work, so I prefer to add new features and keep learning more from my mistakes until we really need this major refactoring.

This is why you should not feel daunted when contributing. We can make mistakes in this project, and if you really don't like the way something is designed then we can think together about a way to improve it.
