### ISSUE TITLE
[Question] Next release?

### ISSUE THREAD

**Issue by stolksdorf** [brrd/Abricotine#253]
When do you think you want to roll out the next release? Anyway we can help at all?

**Comment by brrd** [comment]
Due to a lack of time for my side projects I'm not really involved in abricotine development since the latest release that was published more than a year ago. But hopefully I will be able to work a bit on it some day in the next weeks.

Anyway, IMO the current dev branch is not mature enough to publish it as a new release. I would like to upgrade obsolete dependencies and fix some bugs at least.

**Comment by brrd** [comment]
https://github.com/brrd/Abricotine/releases/tag/0.7.0

**Comment by stolksdorf** [comment]
This is great! Thanks so much for putting in the time to wrap this up. I love using using your tool ❤️
