### ISSUE TITLE
Support for providing custom CSS in HTML export

### ISSUE THREAD

**Issue by Calinou** [brrd/Abricotine#28]
It would be nice if you could append or replace the CSS that's used by default in HTML export, or remove it entirely, without having to edit the resulting HTML file.

There could be support for JavaScript as well, that would be automatically inserted in the `<head>` or at the end of the `<body>`.

**Comment by brrd** [comment]
This feature is planned. A way to manage user-defined templates (in addition to [the default one](https://github.com/brrd/Abricotine/tree/master/default/templates/default) that already exists) will be added in a future release.

**Comment by brrd** [comment]
This feature is available since [version 0.3.0](https://github.com/brrd/Abricotine/releases/tag/0.3.0). It was released a month ago but I totally forgot about this issue.
See [this documentation](https://github.com/brrd/Abricotine/blob/master/docs/templates.md) and [this repo](https://github.com/brrd/Abricotine-templates) which is dedicated to Abricotine export templates.
