### ISSUE TITLE
Can't install with Homebrew

### ISSUE THREAD

**Issue by smotesko** [brrd/Abricotine#29]
```
$ brew cask install abricotine
Error: Cask 'abricotine' definition is invalid: Bad header line: parse failed
```

**Comment by sbruchmann** [comment]
Could not reproduce on OS X 10.11.3. Maybe the cask repository has not been updated yet when @smotesko tried to install [Abricotine](https://github.com/brrd/Abricotine).

**Comment by adidalal** [comment]
This error is not a bug, it's caused by an update to how `homebrew-cask` works. Details can be found [here](https://github.com/caskroom/homebrew-cask#important-december-update-homebrew-cask-will-now-be-kept-up-to-date-together-with-homebrew-see-15381-for-details-if-you-havent-yet-run-brew-uninstall---force-brew-cask-brew-update-to-switch-to-the-new-system).

To fix the issue, please run:
```bash
brew update; brew cleanup; brew cask cleanup
brew uninstall --force brew-cask; brew update
```

If you are still having problems, [open an issue with the appropriate template](https://github.com/caskroom/homebrew-cask#questions-wanna-chat)

**Comment by adidalal** [comment]
(Issues with HBC being unable to install things should be made in caskroom/homebrew-cask). We will be able to assist more quickly there (I only saw this because of a ping from another post)

**Comment by brrd** [comment]
@adidalal Ok, we will redirect to homebrew-cask next time. Thanks.

**Comment by smotesko** [comment]
Thank you @adidalal
