### ISSUE TITLE
show symbols

### ISSUE THREAD

**Issue by DoctorSubtilis** [brrd/abricotine#297]
I use symbols (in open symbol font or similar) but so far I didn't manage to show them properly in abricotine: it's my guilt or it could be an improvement?

**Comment by brrd** [comment]
As a markdown editor, Abricotine is not intended to apply inline styles such as font-style to text strings. Therefore it can't display non-unicode symbols fonts.

To be correctly displayed in markdown, an icon must 1) respect unicode standard, 2) be supported by the font used to display the text (Abricotine uses Fira Code font, but you can customize this). Most [unicode emojis](https://unicode-table.com/fr/emoji/) should work.

Since markdown also supports inline HTML, you can also use a trick like `<span style="font-family: 'YourSymbolsFontName';">paste here the icon text</span>`. It won't be previewed in the editor, but it should export well in HTML and PDF (provided that the symbol font is installed in your OS).

Abricotine dosn't support [GFM emojis](https://gist.github.com/rxaviers/7360908).
