### ISSUE TITLE
Font issue on Windows 10

### ISSUE THREAD

**Issue by szelpe** [brrd/Abricotine#30]
Hi I really like the look & feel of Abricotine editor.

I've noticed an issue with the font on Windows which is kind of strange:

![font-issue](https://cloud.githubusercontent.com/assets/192612/13381338/f127bb7a-de59-11e5-9b05-37117f506ac7.jpg)

It's almost like the anti-aliasing is missing or something similar.

**Comment by brrd** [comment]
I took the time to check antialiasing in the app CSS and I found no problem there. I could also see the same difference between Linux and Windows in the Chrome browser, which makes me think that the problem probably comes from a lower layer. 

You can try to report this issue to [Electron](https://github.com/atom/electron/) but I'm not even sure they can do anything to improve this.

I'm closing this issue as a "wontfix" since I'm pretty sure that it has nothing to do with Abricotine.
