### ISSUE TITLE
CMD + V in the save window throws an error

### ISSUE THREAD

**Issue by maishsk** [brrd/Abricotine#36]
OSX.
When using CMD + V to paste a piece of text (for example copying the title and using that as the name I would like to save the document) an error occurs

A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'webContents' of undefined
    at sendCommand (/Applications/Abricotine.app/Contents/Resources/app.asar/app/abr-menu.js:29:16)
    at /Applications/Abricotine.app/Contents/Resources/app.asar/app/abr-menu.js:37:42
    at MenuItem.click (/Applications/Abricotine.app/Contents/Resources/atom.asar/browser/api/lib/menu-item.js:56:20)
    at Function.delegate.executeCommand (/Applications/Abricotine.app/Contents/Resources/atom.asar/browser/api/lib/menu.js:125:71)

**Comment by brrd** [comment]
Looks like a

**Comment by brrd** [comment]
It's maybe related to #32.

I can not try to reproduce this issue since I don't have OSX, so I need more information.

Does it happen when you use the Paste command by clicking the paste command in the app menu?
Does it happen each time you paste a text in Abricotine using Cmd+V?
Did you close any other Abricotine window before you tried to paste the text?
Are you sure that an Abricotine window is focused when you use the command?

**Comment by maishsk** [comment]
1. Yes. clicking Edit -> Paste throws the same error
2. Yes
3. There is no other Abricotine window open, only my post - and the save Window
4. Yes - definitely 

The only way to actually paste into the file name field - is to right click with the touchpad and select Paste

**Comment by brrd** [comment]
OK, I got it. It's probably related to https://github.com/atom/electron/issues/2331. We need to use menuItems `role` attribute.
