### ISSUE TITLE
Add a .desktop file (archlinux package)

### ISSUE THREAD

**Issue by Hitaro** [brrd/Abricotine#44]
Edit: This question has been edited to be focused on `.desktop ` file

I have installed it by https://aur.archlinux.org/packages/abricotine

I can't find it via Plasma (KDE) desktop dashboard! It's not listed within applications. Why Plasma cannot find it?!

     My OS: Archlinux 64 bit
     My Desktop: Plasma v5.5

**Comment by brrd** [comment]
> I have installed it by https://aur.archlinux.org/packages/abricotine

I was not aware of the existence of this package. It is definitely responsible for the missing link.

Have you tried to run the app from source? See: https://github.com/brrd/Abricotine/blob/master/docs/installation-and-usage.md#building-and-packaging

**Comment by silentboatman** [comment]
I believe the reason you can't find it via the desktop dashboard is because there's no .desktop-file. And building the app from source doesn't generate one. Would be great if Abricotie included one! Here's an example of a .desktop-file: http://pastebin.com/raw/2dgaPHbb

And here's some more links on .desktop-files:

https://wiki.archlinux.org/index.php/Desktop_entries
https://developer.gnome.org/integration-guide/stable/desktop-files.html.en
https://techbase.kde.org/Development/Tutorials/Desktop_File
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

The warnings you get from the terminal is another issue and has to do with (as the warnings says) deprecated code.

**Comment by Hitaro** [comment]
@brrd

I split this to another one: https://github.com/brrd/Abricotine/issues/45

So, this one can be for `.desktop` file issue.

**Comment by brrd** [comment]
> I believe the reason you can't find it via the desktop dashboard is because there's no .desktop-file. And building the app from source doesn't generate one. Would be great if Abricotie included one!

@silentboatman You must see the difference between the app (which is build from source) and its installers (= packages in linux, by instance). The .desktop file is supposed to be a part of the package but it has nothing to do with the app.

As you can read in the documentation ([here](https://github.com/brrd/Abricotine/blob/master/docs/installation-and-usage.md#installation-from-binaries)), installers are not released yet. As I wrote in #8, I would like to provide installers/packages for windows and linux (debian based distros) but it already takes a lot of time to create app binaries for those platforms so I could not get the time to do it. The package installed by @Hitaro is provided by someone else and is not "officially" supported here.

> The warnings you get from the terminal is another issue and has to do with (as the warnings says) deprecated code.

Actually I don't think so. It may be a bug from the app, but since @Hitaro is using an unofficial build we need first to make sure that this issue is not coming from this build. That is why I'm asking him (or someone else who encounters the same issue) to try to run the app from source.

**Comment by brrd** [comment]
@Hitaro We posted our messages at the same time.

> So, this one can be for .desktop file issue.

As I explained in my previous post, the archlinux package that you use is not officially supported. If you want the .desktop file to be added you will need to contact the owner of this package.

So I'm closing this issue as a wont fix.
