### ISSUE TITLE
Is this a joke

### ISSUE THREAD

**Issue by Noomene** [brrd/Abricotine#5]
Half the announced features are simply not working.
Downloaded the 32 bit version to my windows 8 64 .. didn't work! Downloaded the 64bit version. Could run it. But did not do anything of what it announces. No image paste. No auto preview. No nothing basically.

Devs please stop joking please.

**Comment by sbruchmann** [comment]
Hello @Noomene 

> No auto preview.

It is not automatically enabled. There’s an entire menu dedicated to this feature.

**Comment by brrd** [comment]
Hello @Noomene

> Devs please stop joking please.

It's not a joke but a consequence of myself developing Abricotine alone during my free time. Plus it is clearly written in the readme that Abricotine is in a beta stage.

I try to do my best to provide a decent support on Windows. I'm personally a Linux user and I need to find another computer each time I want to test or build the app on Windows. The OSX support [came from another contributor](https://github.com/brrd/Abricotine/pull/2) but I have no clue that everything is working 100% fine with it.

As far as I know Abricotine is working for most users, so what happened to you is probably what we call a bug. I actually rely on users reports (and contributions) to help me finding issues and fixing them in order to improve the app. I think this is the way open source should work. 

I already heard that Abricotine is not working good for everyone, but unfortunately most people who encountered issues just complain as you do, without giving any detailed information such as error descriptions, debug messages, configuration, etc. So I can not do anything at the end.

Once again, it's my free time and I don't want to spend it arguing with people who just criticize, so I'm closing this issue. But if you want to contribute by writing more relevant and precise bug reports, you will be very welcome indeed.
