### ISSUE TITLE
Menue bar not accessable in fullscren mode

### ISSUE THREAD

**Issue by DigitalChiller** [brrd/Abricotine#55]
Problem:
You can't access the menu bar in full screen mode. with a permanent menu bar at the top the full screen mode wouldn't look that nice.
Suggestions:
the menu bar only shows up when you move the pointer to the upper border of the screen so it behaves like a task bar in auto-hide mode.
the menu bar elements are in the right-click menu.
you can hide and show the menu bar.

**Comment by brrd** [comment]
The fullscreen mode depends on [electron](http://electron.atom.io/) which does not provide any API to control the menubar in fullscreen mode, so if you want this to happen you can [create a new issue for electron](https://github.com/atom/electron/issues).

>  the menu bar elements are in the right-click menu.

This is not recommended since the context menu already has a different purpose and could be extended in future releases (with spelling recommendations by instance).

Right now, the only thing you can do is to uncheck the "Show menu bar" option and press the Alt key to show the menubar. It also works in fullscreen mode (tested on linux and windows).
