### ISSUE TITLE
Underlined headers displayed incorrectly

### ISSUE THREAD

**Issue by pierreporte** [brrd/Abricotine#57]
The level 1 and 2 titles, when created using an underlining row of `=` or `-`, are not displayed correctly. The actual text of the title remains in the common style and is not enlarged. Below is a screenshot.

![selection_516](https://cloud.githubusercontent.com/assets/2029853/14274946/9a4cf09a-fb14-11e5-934c-27ed6d94df8f.png)

**Comment by brrd** [comment]
Actually this issue is difficult to fix properly because of CodeMirror parser design (it goes line after line and can not go back to a previous line). In my opinion, this syntax is a tricky feature of markdown which should be avoided whenever possible because it's much harder to handle than the classical `#` expression (regardless of the parsing system). But I agree that it is important to provide support for it. 

Abricotine already supports this syntax in the table of content ([here](https://github.com/brrd/Abricotine/blob/master/app/renderer/abr-pane.js#L60)). We need a new method independent of CodeMirror's parser to parse the content and correct this on editor change.

**Comment by brrd** [comment]
Related feature request in CodeMirror: https://github.com/codemirror/CodeMirror/issues/839

A workaround here: https://github.com/codemirror/CodeMirror/issues/2143#issuecomment-140100969 (but we must check performance on large documents).

**Comment by brrd** [comment]
[CodeMirror 5.27.0](https://github.com/codemirror/CodeMirror/releases/tag/5.27.0) now features a new [`StringStream.lookahead`](http://codemirror.net/doc/manual.html#StringStream) method which can help fixing this. IMO the best solution would be to fix the markdown mode directly into CodeMirror.
