### ISSUE TITLE
Create a Flatpak package for Linux

### ISSUE THREAD

**Issue by Paviluf** [brrd/Abricotine#78]
Hello,

Can it be possible to create a [Flatpak](http://flatpak.org/) package for Linux please ? I want to install Abricotine on Fedora but there is no package available. A Flatpak package will allow Abricotine install to almost every linux distro.

Thanks !

**Comment by nloveladyallen** [comment]
Are you not able to build from source?

**Comment by Paviluf** [comment]
I don't know and I don't want to know ;) Now that there is an easy and somewhat standard way to install applications on Linux nobody should have to build himself an application anymore.

**Comment by brrd** [comment]
> I want to install Abricotine on Fedora but there is no package available.

Normally you can use Abricotine with the provided binary. Isn't it working on Fedora?

> Now that there is an easy and somewhat standard way to install applications on Linux nobody should have to build himself an application anymore

...except that one guy who build the app for you before you can install it :smiley:

Right now few executables are provided: win 64 bits, linux 32 and 64 bits, and OSX when possible (= when someone build it for others). Each time you want to build such a binary, you need to do it from the target OS, that's why I'm using virtual machines for doing this. As you can guess it takes quite a lot of time to build Abricotine for all these platforms.

I think it is more interesting to spend time on fixing bugs and implementing new features than creating binaries/packages/installers. There are plenty of package solutions for Linux today and Flatpak probably is a very good alternative but I also see many of its disadvantages: it is not widely used, it is not available in Ubuntu official repos, it makes [yet another competing standard](https://xkcd.com/927/), it would require more specific development (writing something like https://github.com/unindented/electron-installer-debian, but for Flatpak) ... And in my opinion installing Flatpak on some distros is even more difficult than building Abricotine from source (it needs 4 commands as root on Debian, while building Abricotine is only requires a simple `npm install`).

For these reasons, I prefer to focus on more classical solutions such as deb/rpm.

**Comment by Paviluf** [comment]
> Normally you can use Abricotine with the provided binary. Isn't it working on Fedora?

I didn't try for the moment. I would have preferred a nicely integrated package.

> ...except that one guy who build the app for you before you can install it :smiley:

Yes but it's only one person that make it for everybody and when you create an application it's fairly normal to build it to make it available ;)

Well that's disappointing :( If the devs, in general, don't want to invest time in what will almost certainly be the standard way on Linux to install apps, we will never have an easy and standard way to install apps on Linux.

When you say "it is not widely used", it's the chicken / egg problem. If nobody use Flatpak that pretty sure that it won't be widely used. It's fairly new and it will need time to be broadly used. That said it will be integrated in almost every distro very soon. You are right there is several similar tools available now but Flatpak will almost certainly be the standard. Even if it need 4 commands now to be installed it still fairly simple.

[Libreoffice](https://www.libreoffice.org/download/flatpak/) has started to make a Flatpak package available. Gnome is behind Flatpak so there is obviously [Gnome apps available](http://flatpak.org/apps.html) as Flatpak packages. [KDE](https://community.kde.org/Flatpak) has started work to make their app available as Flatpak packages. Soon, when Gnome Softwares 3.22 is released there won't need to use some command line anymore. A simple double click on the app and it will be installed as Flatpak will be integrated in Gnome Softwares 3.22.

I find this Flatpak thing pretty compelling !

**Comment by brrd** [comment]
> when you create an application it's fairly normal to build it to make it available ;)

Yes, and this is exactly why I'm trying to create builds and fix issues in priority, even if it's less exciting than adding fancy features to the app. I'm developing Abricotine on my free time and I want to find a good balance between boring but important tasks and interesting parts.

> When you say "it is not widely used", it's the chicken / egg problem. If nobody use Flatpak that pretty sure that it won't be widely used.
> (...)
> Libreoffice has started to make a Flatpak package available.

The difference with LibreOffice is that Abricotine is a very small project developed (for 99% of its code) by a single developer, while LibreOffice depends on the Document Foundation which is far more bigger! Such projects are big enough to have a real impact on standards. Apps such as Abricotine (= about 5 000 users as I can guess) just follow the main tendency in order to be accessible to the largest number possible. 

Right now I can see several alternatives to traditional package managers but I can not guess which one will be the main standard tomorrow: maybe it'll Flatpak, but why not Snap, Brew or even [an Electron appstore](https://github.com/electron/electron/issues/673)? I don't want to waste my time developing useless packagers so I prefer to wait and see.

Maybe Flatpak will become the new standard, then someone would create a tool to easily make compatible packages from Electron apps (so it would be easier for small projects to create packages). If so, you can be sure that Abricotine would move to it.

**Comment by Paviluf** [comment]
I just tested the provided binary on my Netrunner 14 install and it work pretty well ;)
It will do the trick for now :-)

I understand and thank you for your time and for Abricotine !

**Comment by brrd** [comment]
> It will do the trick for now :-)

I'm planning to release deb and rpm packages in the same time. Hope I could fix this soon...

**Comment by Paviluf** [comment]
That's great ! I don't know what your plan is but the free [open build service](http://openbuildservice.org/) from opensuse is very great from what I heard.

> A generic system to build and distribute packages from sources in an automatic, consistent and reproducible way. Release your software for a wide range of operating systems and hardware architectures.

**Comment by Lunarequest** [comment]
if someone else were to maintain the flatpak would this be reconsidered?

**Comment by brownc0** [comment]
> > It will do the trick for now :-)
> 
> I'm planning to release deb and rpm packages in the same time. Hope I could fix this soon...

Is an `rmp` release still a possibility?
